name: TestRun
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: Artifacts
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
      
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

- name: Prepare reports
  if: always()
  run: |
    cd frontend
    npm i -g mochawesome-merge
    npm i -g mochawesome-report-generator
    mochawesome-merge test/cypress/reports/mocha/*.json > ./test/cypress/reports/mocha/index.json
    marge --charts=true --showPassed=false -o ./test/cypress/reports/mocha/ ./test/cypress/reports/mocha/index.json
- name: Cypress report
  uses: dmitry/cypress-report-action@v1
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    pathname: frontend/test/cypress/reports/mocha/index.json
  if: always()
   
          

        

      